### ISSUE TITLE
MAP influences pulsewidth when TPS selected as fuelling algorithm

### ISSUE THREAD

**Issue by scudderfish** [noisymime/speeduino#1002]
Tune : https://tunes.speeduino.com/#/t/qJ9XsHH84j/tune/settings/engine_constants
Video: https://youtu.be/INBYySeuQ6A

This could be PEBCAK.  The demo is from 202207.1 running with against an Ardustim board.  If I have MAP selected as the fuelling algorithm, changing MAP changes the PW and changing TPS has no effect.  If I have TPS selected as the algo, then changing TPS changes the PW but also changing MAP changes it.  I had a cursory look at the code and I couldn't immediately see anything obvious.

**Comment by jonbills** [comment]
have you got multiply ve by map:baro set in your ve table?

**Comment by scudderfish** [comment]
You see?  I told you it could be PEBCAK :D
