### ISSUE TITLE
scheduler_calcs.h needs to be included in init.ino

### ISSUE THREAD

**Issue by jonbills** [noisymime/speeduino#1025]
channelNInjDegrees and channelNIgnDegrees (where N is [1...8]) are all used in init.ino, but there is no declaration.
The definition is in scheduler_calcs.cpp and the extern declaration is in scheduler_calcs.h, so scheduler_calcs.h needs to be included in init.ino.

**Comment by jonbills** [comment]
this is wrt master as of 23/03/2023

**Comment by noisymime** [comment]
Fixed in a309659b6966c708d2ad876121b1b260b70a1d82
