### ISSUE TITLE
Spark Table using MAP KPA for load when TPS Control Algorithm is selected

### ISSUE THREAD

**Issue by MykkH** [noisymime/speeduino#1029]
Spark Table using MAP KPA for load when TPS Control Algorithm is selected. 

At first I thought it just wasn't changing the Y-axis labeling, however it still very much used the MAP load values with engine running.

**Comment by jonbills** [comment]
Do you have TPS set as load index in spark settings? 
Add your tune and a log to the issue.

**Comment by MykkH** [comment]
Settings >Engine Constants >Control Algorithm: TPS, is that not the blanket way to set up Alpha-N?

**Comment by LPG2CV** [comment]
VE and spark loads are independant of each other. Look in Spark settings :)

**Comment by noisymime** [comment]
That's working as intended. The option in Engine Settings is for the fuel algorithm with spark having its own load source setting
