### ISSUE TITLE
Implement "Always On" Strategy on Stepper Control

### ISSUE THREAD

**Issue by zukhe** [noisymime/speeduino#1031]
Implement the strategy that imobilizes the stepper from moving freely, like it's done on Megasquirt:

![image](https://user-images.githubusercontent.com/126247284/230928810-73de4d0f-bfe5-48c5-9cf2-05db45dfb715.png)

This will addres for motors that "free wheel" when there's no current applied.

**Comment by VitorBoss** [comment]
Just set the cool time to 0

**Comment by zukhe** [comment]
Not the same.

Em seg., 10 de abr. de 2023 18:21, Vitor Moreno B. Sales <
***@***.***> escreveu:
