### ISSUE TITLE
Typo in Case 55 of init.ino?

### ISSUE THREAD

**Issue by gwynethh** [noisymime/speeduino#1034]
starting at line 2385
pinSpareLOut1 = 29; //low current output spare1
pinSpareLOut2 = 26; //low current output spare2
pinSpareLOut3 = 28; //low current output spare3
pinSpareLOut4 = 29; //low current output spare4

Two listings for pin 29?
But I'm still a noob at this.

**Comment by evan-chaney** [comment]
I feel like this might be ok since it's been there for 4 years according to the blame.
@noisymime you authored this so maybe you could confirm/close this issue?
https://github.com/noisymime/speeduino/blame/d2aacf2933a434b47ea9b3b29afe4967361cb837/speeduino/init.ino#L2301

**Comment by noisymime** [comment]
This is simply a placeholder value so that the variable is not initialised to something that might cause problems. The board doesn't have a 4th spare output driver so this will never be used anyway.
