### ISSUE TITLE
HalfsyncToFullSync issues found on testing.

### ISSUE THREAD

**Issue by TBAMax** [noisymime/speeduino#1051]
When switching from half to full sync at engine startup, the closeInjector and openInjector assignments are changed. But this creates the possibility that when this is done during the fuel or ignition pulse, the started pulse on some channel is not turned off. This shows up occassionally on logic analyser when testing(image below). 
Indicated by very long injection pulse. This happens only occassionally, but will probably flood the corresponding cylinder.
Probably this might be  already a known issue.

<img width="960" alt="FUELpulse" src="https://github.com/noisymime/speeduino/assets/36799067/e3b98afe-f0c8-4857-8fd6-6309e8a17adf">

**Comment by VitorBoss** [comment]
Yes, that could happen if the CAM sensor came after a pulse started, this is easily avoided by checking for stopped timers before changing.

**Comment by TBAMax** [comment]
> 



> Yes, that could happen if the CAM sensor came after a pulse started, this is easily avoided by checking for stopped timers before changing.

Ok, I am on it. Hoping to get the PR submitted soon.

**Comment by noisymime** [comment]
Fixed with #1052
