### ISSUE TITLE
Addition of VVT

### ISSUE THREAD

**Issue by Jama-** [noisymime/speeduino#109]
I believe it would be a great addition to the speeduino if closed loop VVT could be added.
I personally have a Ford ST170 engine and am wiring it up with another ECU which has integrated VVT control.
I can create a small harness adapter and swap that out for a Speeduino and do testing at my end.

I have been reading about it over the weekend and found these resources which might be helpful.

I believe a basic initial implementation with just variable P, I and D values would be good.
Then maybe once some are tested out presets added with known good values. 

http://www.ni.com/tutorial/13609/en/

http://www.turbosport.co.uk/showthread.php?t=478299

https://www.egr.msu.edu/zhug/Journal%20Articles/Modeling%20and%20control%20of%20an%20electrical%20variable%20valve%20timing%20actuator.pdf

https://www.miataturbo.net/megasquirt-18/itt-ms3x-vvt-settings-tuning-64590/

**Comment by dxControl** [comment]
Yes a very useful addition.
Angular variable vvt has been discussed for some time now and some code had been pr'ed before
It needs more work with multi tooth cam decoding still .
Search on forum for ongoing discussions about implementation too.

**Comment by dancake2017** [comment]
Agreed. Multi platform would be ideal, but Vehicle specific (like Miata 99-05 or Ford) could be rolled in as requested. ?

**Comment by noisymime** [comment]
Closing as this is in place for the patterns mentioned
