### ISSUE TITLE
BOM for 0.4.3d missing some components

### ISSUE THREAD

**Issue by evan-chaney** [noisymime/speeduino#1095]
I ordered the components from the 0.4.3d board using the BOM on the wiki and when it came time to assemble I was missing some of the required components.

- Screw terminals
- Male header pins
- Jumpers (not sure if this is the right word, the things that connect the male pins on JP*)

**Comment by noisymime** [comment]
Closing as this needs to be on the https://github.com/speeduino/hardware repo
