### ISSUE TITLE
the new serial 2 comms broke can bus data in

### ISSUE THREAD

**Issue by Fera31** [noisymime/speeduino#1116]
the can bus broadcast work great but canbus input communication does not work.
I'm trying to find what is the cause of the problem

i remame comms_secondary.cpp to comms_secondary.ino and works. 
can someone explain me this ? 
Does this problem only happen to me? or is it a real code problem?

**Comment by noisymime** [comment]
What hardware are you running on and are you compiling through the Arduino IDE or PlatformIO?

**Comment by Fera31** [comment]
> What hardware are you running on and are you compiling through the Arduino IDE or PlatformIO?

stm32f407vet6
PlatformIO

**Comment by noisymime** [comment]
This should be resolved now on master. If you're able to try the current master code and confirm, that would be good
