### ISSUE TITLE
Add sequential capability to daihatsu+1

### ISSUE THREAD

**Issue by runesmdk** [noisymime/speeduino#1126]
Trigger contains both speed and home signal.

Possible to make it sequentially capable? 

Would love to do away with my old rotorbutton and rotor cap :)

**Comment by noisymime** [comment]
I can't see any reason why this won't just work if the sequential flag is turned on. It's already tracking crank angle over 720 degrees, so it should really be that simple. I'll give it a try and see if it simply works already

**Comment by runesmdk** [comment]
> I can't see any reason why this won't just work if the sequential flag is turned on. It's already tracking crank angle over 720 degrees, so it should really be that simple. I'll give it a try and see if it simply works already

Love it, cant wait to try it
