### ISSUE TITLE
3 cyl wasted cop vs 6cyl wasted spark

### ISSUE THREAD

**Issue by runesmdk** [noisymime/speeduino#1132]
3cyl wasted cop doesnt run right, a cylinder is missing. Tried reversing coil 2-3, but that just made it worse.  Setting it as 6cyl wasted spark it runs right, with original coil wiring too.

**Comment by runesmdk** [comment]
Added: 202305 firmware

**Comment by noisymime** [comment]
Is one of the 3 spark outputs not firing at all, does it fire a the wrong time? Wasted COP on a 3 cylinder is the same as just normal wasted spark isn't it?

**Comment by runesmdk** [comment]
All 3 fire, timing is off.
Talked with pasi earlier. He said the description of said modes arent correct, and it should work with wasted spark (not cop) in 3cyl setting as well.

So seems to be a description issue. 

Car runs for now :)

**Comment by noisymime** [comment]
OK, I see the problem here. There's an init case for Wasted COP that hasn't considered 3 cylinder. Fix coming shortly
