### ISSUE TITLE
Dropbear secondary serial does not work

### ISSUE THREAD

**Issue by paulgilc** [noisymime/speeduino#1135]
Known issue with secondary serial on Dropbear.  Code points to Serial2 but should be Serial1 to enable the use of the J4 header.  Just setting to Serial1 in the secondary serial code does not work as has been advised and instructed to do.  If you set it to Serial6, and then use the pins on the Teensy for Tx6-Rx6, it then works.

**Comment by paulgilc** [comment]
I can confirm that changing the below in "comms_secondary.cpp". Current Master Code.  Works.
Setting it to Serial1 does not.
#elif defined(CORE_TEENSY)
  HardwareSerial &secondarySerial = Serial6;

**Comment by noisymime** [comment]
This should be resolved in master now. Please test and let me know if you're still seeing issues.
