### ISSUE TITLE
STM32 LIBDIVIDE Division by 0 causes mcu hang 

### ISSUE THREAD

**Issue by gdiciocco** [noisymime/speeduino#1162]
https://github.com/noisymime/speeduino/blob/fff315aa452a31a36548028c2a74540817f91e00/speeduino/decoders.cpp#L126

https://github.com/ridiculousfish/libdivide/blob/ee2a872b85648b16c0a65faa8cb646fa7e9e903a/libdivide.h#L95

Division by 0 on non-AVR mcus causes libdivide call abort() which ends up in a noreturn 

Issue was submitted to libdivide:
https://github.com/ridiculousfish/libdivide/issues/112

**Comment by noisymime** [comment]
This is largely resolved by 7c26de6333d0cc28b14cb1803e2cea242a8054d6

It doesn't specifically check for a 0 value, but will mean that a new board where this is defaulted to 0 will not freeze on first startup
