### ISSUE TITLE
Is primary injector pulse width calculation correct in calculateStaging(), when stagingMode is STAGING_MODE_AUTO?

### ISSUE THREAD

**Issue by ChrisNisbet01** [noisymime/speeduino#1172]
I think I might have found a wee bug in calculateStaging() relating to the primary injector pulsewidth when stagingMode is STAGING_MODE_AUTO.

The incoming PW value first has the injector opening time subtracted off it (currently on line 471) to simplify the calcs done later on in the function. There is an accompanying comment reassuring the reader that this time is added back later on.

In STAGING_MODE_TABLE we can see this happen (currently on line 480)...
currentStatus.PW1 += inj_opentime_uS;

In STAGING_MODE_AUTO we see PW1 get assigned the value of tempPW1 (currently on line 497), but this value (according to the comments) does _not_ include the injector opening time. If tempPW1 is above the pwLimit then PW1 is set to the limit (which seems correct), but otherwise PW1 is left at the value of tempPW1, which doesn't include the opening time.

If tempPW1 is <= pwLimit, doesn't PW1 need to have inj_opentime_uS added back onto it?

My apologies if I've missed something and this isn't actually a bug.

**Comment by noisymime** [comment]
At a quick glance you may be correct with this. I'll spin up a test and confirm that it needs to be added back on there also.
