### ISSUE TITLE
Increase squirts-per-cycle

### ISSUE THREAD

**Issue by PSIG-dev** [noisymime/speeduino#135]
Speeduino users could benefit from more than 1 or 2 squirts-per-cycle for a number a useful reasons.

Beyond the obvious potential for improved fuel distribution in certain engines and setups; ultimately, semi-automated setting of injector latency (dead time), voltage compensations, and other important functions could stem from this.

**Comment by noisymime** [comment]
This was brought in with commit 8706c107fb56cc50da3f631cdc8b3d17b005b1b8
