### ISSUE TITLE
Allow negative retard values for IAT based ignition adjustment

### ISSUE THREAD

**Issue by noisymime** [noisymime/speeduino#140]
Per thread: https://speeduino.com/forum/viewtopic.php?f=12&t=1838

In the IAT Timing retard curve, allow negative values so that more advance can be configured when cold

**Comment by PSIG-dev** [comment]
Another cold-temp timing advance request:  https://speeduino.com/forum/viewtopic.php?f=12&t=2355#p29089

**Comment by lsdlsd88** [comment]
I think this issue can be closed now? https://github.com/noisymime/speeduino/pull/220

**Comment by noisymime** [comment]
Yep, this one has been addressed in #220
