### ISSUE TITLE
pageReadCommand incorrectly specified in speeduino.ini

### ISSUE THREAD

**Issue by scudderfish** [noisymime/speeduino#155]
I've been trying to diagnose why some Speeduino users are having trouble with MSDroid (I'm a sometimes developer on MSDroid) and it seems there is an error in speeduino.ini.

The current pageReadCommand is defined as "p%2i%2o%2c%v"  which basically breaks down to :-
p - read page
%2i - page index
%2o - offset
%2c - count
%v - value (i.e. page contents)
The %v only belongs on write commands.  As it currently stands MSDroid faithfully sends the requested contents of the page with the page read command and weird things happen depending on the contents of that data as Speeduino is not expecting it.  TunerStudio seems to silently squeltch the misconfiguration, MSDroid does what it is told to do.  If you change the pageReadCommand values to "p%2i%2o%2c" then everyone is happy.

**Comment by noisymime** [comment]
Thanks for the report, this should be easily fixed! if I had to guess, I'd say this was simply a copy/paste that never got picked up because it worked in TS, but it is a little sloppy. 

I'll have a commit in shortly for this.
