### ISSUE TITLE
MegaLogViewer won't show the spark map from the opened tune if saved from the June release

### ISSUE THREAD

**Issue by ric355** [noisymime/speeduino#160]
I have some saved tunes that were saved when I was using the February 2018 release. I am now on the June release. If you open MegaLogViewer and open a log file, then open the tune that matches it, then:

* if the tune was saved with the February 2018 release then it is possible to have both the spark map and the fuel map shown alongside the data, on the right of the screen
* if the tune was saved with the June 2018 release then only the ve table can be selected.

I have taken a look within the files and found that the problem is caused by a change to the name of the Y axis bins for the spark table. The February tunes I have saved call this "mapBins2" but the tune saved from the June configuration calls it "ignLoadBins". If I edit the file and change it back to "mapBins2" then I can view the spark table again.

**Comment by noisymime** [comment]
MLV appears to use some form of reg ex matching for these that I can't find all the details of. As frustrating as it is, I'll revert the name on this for now to get it working again.
