### ISSUE TITLE
Cranking Enrichment and IAC Cranking 

### ISSUE THREAD

**Issue by Iliz79** [noisymime/speeduino#178]
There is used "if( BIT_CHECK(currentStatus.engine, BIT_ENGINE_CRANK) )" and that dosen't work.
Cranking enrichment table is not doing anything same thing in idle IAC PWM.

BIT_CHECK is not working in idle.ino and correction.ino.

**Comment by noisymime** [comment]
I'm not able to reproduce this for the cranking enrichment. That seems to be working fine as far as I can see.

The idle control is actually outputting correctly, but there is a bug where the idleLoad value is not being updated when in cranking. I'll get this updated shortly.
