### ISSUE TITLE
Bluetooth via secondary serial

### ISSUE THREAD

**Issue by Autohome2** [noisymime/speeduino#184]
On teensy, Sam and potential other MCU the usb is native so the Bluetooth connection for tuning cannot be achieved as is with the mega2560 board.
Add the missing commands to secondary serial to enable full operation by TS through a Bluetooth module connected to the secondary serial pins
Existing commands must not be broken due to existing users of secondary serial and their devices.

**Comment by noisymime** [comment]
This should be covered by the current secondary serial implementation.
