### ISSUE TITLE
Ignition Pulse Generation

### ISSUE THREAD

**Issue by WirelessHubMaster** [noisymime/speeduino#192]
Hey guys, I am trying to generate continuous ignition square pulses in tuner studio when compared to the missing teeth signal. Could you guys please guide me in the process. Thanks in advance!

**Comment by Old-Grey6** [comment]
I'm pretty sure this area is only for issues.

If you want to know triggering the Speedy, try my videos.
https://youtu.be/tUrq7uhv7Eg
