### ISSUE TITLE
Idle Up feature seems to be missing a setting

### ISSUE THREAD

**Issue by ric355** [noisymime/speeduino#196]
I was looking at the idle up feature and it seems like it has some of the implementation missing. You can select the pin and turn it on, and change the polarity, but there is no way to define how the idle should change. 

I can see the ini file has an entry for idleUpAdder, but it hasn't been added to the idle up dialog.

I can also see the code uses the value from the config page in various different ways depending on the type of idle valve in use.

Just a mistake that it hasn't been added to the dialog, or are there other reasons why it isn't fully enabled?

**Comment by noisymime** [comment]
Wow, I don't know how I missed that one, yeah it should've simply been on that dialog. I originally had these on the Idle Settings dialog, then at the last minute moved them onto their own, but obviously missed that field. 

I'll get it added shortly. Thanks
