### ISSUE TITLE
 PROBLEM WITH CONNECT THE FIRMWARE 

### ISSUE THREAD

**Issue by MasqueRacing** [noisymime/speeduino#2]
HEY BROTHER , PLEASE HELP ME...
 I HAVE A PROBLEM WITH CONNECT THE FIRMWARE TO ENTER IN THE (MEGASQUIRT SOFTWARE) THE (IDE) DETECT A PROBLEM , BUT NOT IS OF THAT YOU HAVE IN YOUR PAGE. 

I HAVE A DCCDUINO MEGA 2560  AND THE CONFIGURATION IN IDE ITS OK , I CAN UPLOUD OTHER SKETCH FROM THE LIBRARY, EXAMPLE WITH BLINK ITS OK.. PLEASE SOLVE THE PROBLEM CODE OR GIVE ME A GOOD PRICE FOR ALL ARDUINO ECU FULL MADE!
THANK YOU, SORRY BY MY ENGLISH I AM OF PUERTO RICO (SPANISH)

GOOD WEEK,
BEST REGARDS!!!

**Comment by noisymime** [comment]
Closing this issue as no specific bug was found here. Please log a new bug if there is a genuine issue.
