### ISSUE TITLE
201902 Dwell voltage compensation possible 255 roll over issue

### ISSUE THREAD

**Issue by ESDave05** [noisymime/speeduino#203]
SW Version: 2019 Feb Release
Test Environment: Bench - "JimStim" simulating crank / cam reference, pots for sensor inputs etc...
HW: MX5 PNP

Preconditions:
![image](https://user-images.githubusercontent.com/47916459/53285856-18247d00-37ba-11e9-9e2d-5cb76a436b6a.png)

![image](https://user-images.githubusercontent.com/47916459/53285990-fdeb9e80-37bb-11e9-9663-9e79fd9652b3.png)

As i ramp voltage up and down in crank I see some bizarre behavior with the dwell:

![image](https://user-images.githubusercontent.com/47916459/53286040-8a965c80-37bc-11e9-9c6a-5bece9164b2a.png)

Issue:
Dwell is not clamped to max
Dwell seems to "wrap around" giving undesired output

**Comment by noisymime** [comment]
Thanks for the report. 

I'll check this out ASAP

**Comment by noisymime** [comment]
I've confirmed that there is a bug in how the dwell is reported in TunerStudio (And the log) if it exceeds 25.5ms. The unit itself will still continue to output dwell times over 25.5, but the number in TunerStudio is looping. 

This is very much an edge case as dwell times over 25.5ms are fairly unrealistic, but I will make sure that this is reporting correctly going forward. Again, i'd stress that the actual ignition output will still dwell at the correct time, it's only the value displayed in TS that is wrong
