### ISSUE TITLE
TS Command "P9L" does not terminate

### ISSUE THREAD

**Issue by TradieUte** [noisymime/speeduino#221]
line 1263 of comms.ino contains an invalid compare.

Original (commented) line and change follows:-

//          for (pnt_configPage = &configPage9; pnt_configPage < ((byte *)pnt_configPage + 128); pnt_configPage = (byte *)pnt_configPage + 1)

          for (pnt_configPage = &configPage9; pnt_configPage < ((byte *)&configPage9 + (EEPROM_CONFIG9_END - EEPROM_CONFIG9_START)); pnt_configPage = (byte *)pnt_configPage + 1)

**Comment by noisymime** [comment]
Thanks for the report, I'll fix shortly. 

I'll likely use the `npage_size` array rather than the EEPROM storage locations, but it will ultimately. give the same result.

**Comment by noisymime** [comment]
Assuming you're referring to this line: https://github.com/noisymime/speeduino/blob/master/speeduino/comms.ino#L1218

It's worth pointing out that this should only be affecting the `useChar` version, which is the one that prints out the table values in human readable format. It's not the call used by TS.

**Comment by TradieUte** [comment]
Sent from Samsung tablet.
-------- Original message --------From: Josh Stewart <notifications@github.com> Date: 16/4/19  15:01  (GMT+10:00) To: noisymime/speeduino <speeduino@noreply.github.com> Cc: TradieUte <xalaw@ozemail.com.au>, Author <author@noreply.github.com> Subject: Re: [noisymime/speeduino] TS Command "P9L" does not terminate (#221) Assuming you're referring to this line: https://github.com/noisymime/speeduino/blob/master/speeduino/comms.ino#L1218
It's worth pointing out that this should only be affecting the useChar version, which is the one that prints out the table values in human readable format. It's not the call used by TS.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.That's the one. I was looking at the tables in hrf,  and everything locked up at table 9. 
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/noisymime/speeduino","title":"noisymime/speeduino","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/noisymime/speeduino"}},"updates":{"snippets":[{"icon":"PERSON","message":"@noisymime in #221: Assuming you're referring to this line: https://github.com/noisymime/speeduino/blob/master/speeduino/comms.ino#L1218\r\n\r\nIt's worth pointing out that this should only be affecting the `useChar` version, which is the one that prints out the table values in human readable format. It's not the call used by TS. "}],"action":{"name":"View Issue","url":"https://github.com/noisymime/speeduino/issues/221#issuecomment-483511884"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/noisymime/speeduino/issues/221#issuecomment-483511884",
"url": "https://github.com/noisymime/speeduino/issues/221#issuecomment-483511884",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by TradieUte** [comment]
Have reviewed the change and fear I may have confused the real issue by emphasizing the change in age size.
The issue is that the pointer comparison pnt_configPage < ((byte *)pnt_configPage + 128) never returns false as pnt_configPage is continually incremented.
The clause should read pnt_configPage < ((byte *)&configPage9 + 128)

**Comment by noisymime** [comment]
I really shouldn't code without coffee :D

You're 100% right, I'll fix shortly (Though it definitely should be 192 rather than 128, though that is taken care of with the nPage_size[] reference)
