### ISSUE TITLE
Injector dead time corrections should act on dead times only

### ISSUE THREAD

**Issue by bera-n** [noisymime/speeduino#233]
As I understand the injector latency  voltage correction acts on the "fuel" pulsewidth. Wouldn't it be more logical to apply it directly to the dead time instead? 

This I think would be beneficial at around idling where the dead time is a significant part of the pw and voltage tend to drop.

Drawback is that you would need some reasonable correction data on your injectors.

**Comment by runesmdk** [comment]
It does exactly that. Injector latency IS deadtime
