### ISSUE TITLE
Adding -Wall -Wextra build flags to prevent bugs

### ISSUE THREAD

**Issue by brunob45** [noisymime/speeduino#234]
In platformio, we should add the -Wall and -Wextra flags to the compilation build_flags, like so:
```
[env:megaatmega2560]
platform=atmelavr
board=megaatmega2560
framework=arduino
build_unflags = -Os
build_flags = -O3 -ffast-math -Wall -Wextra
lib_deps = EEPROM
```
These flags enable more compilation warnings, and can help prevent bugs.

For example, the new warnings would be like :
`speeduino/table.ino:339:43: warning: comparison is always true due to limited range of data type [-Wtype-limits]`
or
`speeduino/crankMaths.h:15:118: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]`

If we want to take it a step further, we could even add the -Werror flag, which would make every warning an error :
`build_flags = -O3 -ffast-math -Wall -Wextra -Werror`

Here's a list of all the warnings for the branch master, at this moment : [warnings.txt](https://github.com/noisymime/speeduino/files/3350468/errors.txt)

**Comment by noisymime** [comment]
Makes sense to me. Most of this stuff _should_ have been picked up with the MISRA static scans, but I'll tidy these few up and make the extra warnings part of the standard build.
