### ISSUE TITLE
Ignition advance unstable in negative value

### ISSUE THREAD

**Issue by elyrizal** [noisymime/speeduino#235]
Firmware 201905 where ignition advance vs temperature were first introduce. On cold start where it in positive value for advance, should be no problem. But when i pull down to negative value (retard) after 85 degree celcius, i can see ignition angle display + or - 10 degree from current table but my retard only -2 at 102 degree max. Some time it go advance and sometimes it go to retard. Set back to 0, everything will go normal

Thank you

**Comment by noisymime** [comment]
Hi, this is is a known issue in the 201905 version. It's been fixed in 030b88b57869b25ddbc2da77f88973f09043243d
