### ISSUE TITLE
Error loading firmware definition in TunerStudio 3.0.28

### ISSUE THREAD

**Issue by UnicodingUnicorn** [noisymime/speeduino#243]
When I try to load `speeduino.ini` in TunerStudio MS Lite! 3.0.28 as per these [instructions](https://speeduino.com/wiki/index.php/Connecting_to_TunerStudio), TunerStudio gives me the following message:

```
Error loading ECU configuration.
Message:
A newer version of this application is required to load ECU Definition File speeduino.ini
```

and

```
Error setting configuration to comm settings.
Reported Error:
Ecu Configuration not valid.
```

This could be related to the lack of a Comms Settings panel appearing after the Configuration panel.

**Comment by noisymime** [comment]
The current master code on GitHub requires the beta version of TunerStudio: http://www.efianalytics.com/TunerStudio/beta/
