### ISSUE TITLE
Missing tooth decoder will sync with only crank, even if seq is used somewhere

### ISSUE THREAD

**Issue by noisymime** [noisymime/speeduino#259]
See: https://www.facebook.com/groups/191918764521976/permalink/957900587923786/

The missing tooth decoder will flag sync as being achieved based only on the detection of the missing tooth, even if sequential fuel or ignition is selected.

This is unlikely to impact 4 cylinder setups where this will effectively just cause things to operate in wasted until the cam signal is detected, but is a problem on 3 and 5 cylinder setups with COPs

**Comment by Tjeerdie** [comment]
I have seen something similar for the STM32 (must obviously be the same). BUT there was a problem with the injector pulse of injector 3 using crank only 4 cylinder full sequential (i think channel 3,I will check the number when i get home). injector 3 will skip a pulse every other crank rotation. (i guess the cycle missing the cam sensor). All the other injectors and all ignition channels work as wasted spark indeed.  

Maybe the same problem is there in the mega? I did not test on the mega.
