### ISSUE TITLE
fix for issue #296

### ISSUE THREAD

**Issue by gilberninvader** [noisymime/speeduino#297]
Hi. I have tested the fix for issue #296 (MAP spikes up during cranking). I downloaded the master file and tested on the bench using adjustable PWM device as trigger (basic distributor). During cranking the engine revolutions are now divided by 4 - this has always worked perfectly in the past. Above cranking they revert to normal, correct values. The spike in MAP has been  fixed.

**Comment by noisymime** [comment]
Thanks for the report. Was a (dumb) regression introduced a few commits ago. Fixed now.
