### ISSUE TITLE
Miata 1.6 201911, 201905 base tunes corrupted

### ISSUE THREAD

**Issue by vapidorder** [noisymime/speeduino#304]
AFR ratio load bins all got changed to value "510". Compared to 2019.05 tune, priming pulse width values lost (curves flattened), ASE Enrichment % values lost (curves flattened).  AFR table issue verified repeatable with two members of Speeduino Tuning Facebook group and verified in code rows 459 thru 474.
https://github.com/noisymime/speeduino/blob/57bfc3634820b73d1df0058ee71ca45f764db968/reference/Base%20Tunes/NA6%20PNP%20base%20tune.msq#L459
The repeating "510" value also appears to have been mixed into the staging table
https://github.com/noisymime/speeduino/blob/57bfc3634820b73d1df0058ee71ca45f764db968/reference/Base%20Tunes/NA6%20PNP%20base%20tune.msq#L736
and the in the rotary split bins.
https://github.com/noisymime/speeduino/blob/57bfc3634820b73d1df0058ee71ca45f764db968/reference/Base%20Tunes/NA6%20PNP%20base%20tune.msq#L1125
I'm not sure if this is supposed to be the case for any of these.

![Annotation 2020-01-14 210259](https://user-images.githubusercontent.com/59948545/72494968-5cf24180-37da-11ea-8c01-4754dfc09aba.jpg)

**Comment by pazi88** [comment]
I noticed this too in my base tunes. So not specific for miata base tune only. It has come in nee fw version. I recommend checking all base tunes 2019.05 onwards.
