### ISSUE TITLE
Injection angle (de)limitation

### ISSUE THREAD

**Issue by muuris** [noisymime/speeduino#306]
I think at least in sequential injection setups the injection angle shouldn't be limited to 0..360°. I've experimented removing this limitation in my sequential setup and found my engine works clearly better when I inject to open intake valve. I couldn't get AE and cold starts working properly at freezing temps with (E85 and) the 0..360° limitation.

**Comment by noisymime** [comment]
The trigger angle range is -360 through to +360. Is this the range you're referring to?

**Comment by muuris** [comment]
Not trigger angle, but injector close angle (Settings / Injector characteristics).

**Comment by noisymime** [comment]
I've added an injector timing curve for this now with a 0-720 range. Needs final testing, but seems to be working.

**Comment by muuris** [comment]
That's a great addition!

**Comment by noisymime** [comment]
Closing this issue as everything seems to be working fine with the new variable timing curve
