### ISSUE TITLE
Typos in speeduino.ini

### ISSUE THREAD

**Issue by roskoant** [noisymime/speeduino#33]
There's a typo in speeduino.ini.
When you go to Tuning -> Acceleration Wizard you can see "Accel Time(ms)", but when you hold your mouse over the "?", the text shown is "Duration for accel enrichment(s)." So seconds or milliseconds?

Also, the window is called "Acceleration Enrichment", but in the menu it shows as "Acceleration Wizzard".

**Comment by noisymime** [comment]
Thanks for the report. The tool tip was picking up TS default values, which weren't right. Milliseconds is correct. Naming will be made consistent too

A fix for both of these things will go in shortly.

**Comment by noisymime** [comment]
Resolved in last commit. Thanks again
