### ISSUE TITLE
200202 release

### ISSUE THREAD

**Issue by TradieUte** [noisymime/speeduino#369]
Setting up for 8 channel sequential. In function calculateIgnitionAngles(), calculations for 6 cylinder, channels 4 to 6 are missing; 8 cylinder, channels 5 to 8 are missing.

**Comment by noisymime** [comment]
This looks like it's resolved in current master. Have you tried the master branch?

**Comment by TradieUte** [comment]
Sorry, should have checked. Mind in isolation mode.Sent from Samsung tablet.
-------- Original message --------From: Josh Stewart <notifications@github.com> Date: 27/4/20  14:58  (GMT+10:00) To: noisymime/speeduino <speeduino@noreply.github.com> Cc: TradieUte <xalaw@ozemail.com.au>, Author <author@noreply.github.com> Subject: Re: [noisymime/speeduino] 200202 release (#369) 
This looks like it's resolved in current master. Have you tried the master branch?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/noisymime/speeduino/issues/369#issuecomment-619718651",
"url": "https://github.com/noisymime/speeduino/issues/369#issuecomment-619718651",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by noisymime** [comment]
Closing as this is resolved in master
