### ISSUE TITLE
Cooling Fan disable on Cranking

### ISSUE THREAD

**Issue by joelgross123** [noisymime/speeduino#383]
I have speeduino on a 383 stroker small block Chevy.  I have multiple cooling fans to cool my sandcar in a rear-mount radiator configuration.  Currently when the cooling fans are enabled it draws alot of current.  When the engine is already at temperature and the engine is restarted, having the cooling fans enabled at key on (speeduino boot-up) complicates things.  I would like to see a feature to disable cooling fans during cranking mode until the engine has had a chance to hit idle rpm.  This would be a big advantage to my application.  Also this may help others tune in getting engine to stable idle rpm before large current load is applied.

**Comment by noisymime** [comment]
<img width="492" alt="image" src="https://user-images.githubusercontent.com/138502/82164270-2563e500-98f3-11ea-921f-60a4e8d25c57.png">

Option added

**Comment by joelgross123** [comment]
Thanks Josh. This looks perfect!

Joel
