### ISSUE TITLE
August release, Teensy 3.5, PINS 29/30 rendered useless by release

### ISSUE THREAD

**Issue by sbtoonz** [noisymime/speeduino#456]
Unable to use pins 29/30 on the august release

only changes noteable were that interrupt timers were introduced to the teensy board file 

I am not sure how to isolate the change that would have crippled pin 29/30 I will update the issue as I find more

**Comment by noisymime** [comment]
This looks to have been introduced with commit 58200f8707f2f359e1fa7debee3e6e69032818d8

Given pins 29 and 30 are the alternate CAN pins, this makes some sense. I'll keep digging and see what I can find here.
