### ISSUE TITLE
VVT bugs in 202008

### ISSUE THREAD

**Issue by pazi88** [noisymime/speeduino#459]
In 202008 release (and in current master) the VVT output gets stuck at 100% duty in open and closed loop modes. And on on/off mode the output gets stuck at 0% duty. The duty gauge in TS works as it should but the actual output signal for VVT solenoid gets stuck to that 0% or 100% duty.

I'm creating this issue, so that the bug doesn't get forgotten. I have done fix for the output getting stuck at 100%: https://github.com/noisymime/speeduino/compare/master...pazi88:VVT-fix

But can't seem to figure out why the output gets stuck at 0% duty in on/off mode. The output works few times from 0% duty to 100% duty and then gets stuck to 0%.

**Comment by noisymime** [comment]
Just to check, is this still an issue in master? If so I'll look at it ASAP ahead of the next release

**Comment by pazi88** [comment]
@noisymime Yes it is. There is also another, which is that if the missing tooth cam trigger event comes after 127 crank degrees, the value send to tunerstudio overflows. You don't notice that at all, but if you try to use closed loop vvt feature with overflowing cam degree value, the PID wont work at all.

I have fixed the overflow and stuck to 100% problems in PR #461 but the stuck at 0% wheb using open loop still remains mystery for me

**Comment by pazi88** [comment]
This all is fixed in 202108
