### ISSUE TITLE
Programmable outputs with 2 conditions; #2

### ISSUE THREAD

**Issue by bap168** [noisymime/speeduino#468]
I am trying to use one of the programable outputs to control a solenoid.  The issue is that the second condition doesn't do anything. My first condition is TPS > 90% and the second is kpa < 160 with the AND operator. I can switch their position but either way it behaves as though the second condition isn't activated. 
This built 202008

**Comment by VitorBoss** [comment]
That issue was already pointed at #464, the problem was found and the fix is awaiting approval. You can close it.

**Comment by bap168** [comment]
I am only using one rule though.  Is this the same issue?

**Comment by VitorBoss** [comment]
Yes, the problem is on second condition
