### ISSUE TITLE
n2o control activation ... 50% map diference 

### ISSUE THREAD

**Issue by Fera31** [noisymime/speeduino#533]
in speeduino.ini  i change   
n2o_maxMAP          = scalar, U08,      77,      "kPa",      2.0,   0.0,  0.0,  511.0,      0
for 
n2o_maxMAP          = scalar, U08,      77,      "kPa",      1.0,   0.0,  0.0,  511.0,      0
and work. i dowt know if ok. but the problem is solved

can someone check this out?

**Comment by noisymime** [comment]
Thanks for the report. Fixed now
