### ISSUE TITLE
comms.ino: receiveValue(): could overwrite random memory

### ISSUE THREAD

**Issue by adbancroft** [noisymime/speeduino#541]
wmiMapPage has a 80 byte "gap" in it's virtual addressing between wmiTable & dwellTable. There is no protection if TS is configured incorrectly and tries to write a byte in that gap: the write will go through & overwrite some random memory location.

**Comment by adbancroft** [comment]
PR incoming

**Comment by pazi88** [comment]
The VVT2 map is supposed to go in that gap.

**Comment by adbancroft** [comment]
Yup, it's a minor bug at best
