### ISSUE TITLE
Teensy Analog input @ A6 doesn't work

### ISSUE THREAD

**Issue by transi01** [noisymime/speeduino#579]
Hey Guy's,

it looks like the analog input A6 doesn't work with teensy3.5.
Have done tests with latest two Firmware versions (202012 and 202103) A6 is not useable for eg 2nd baro sensor...... it alway's display's a fix value but not the same as for another analog input port when not connected........ maybe Bug in Firmware

Thanx,

// Transi

**Comment by transi01** [comment]
Sorry, was aProblem of the board..... works .... never mind

**Comment by plazomat** [comment]
Hi I had a similar issue and believe it’s a bug as well…

 

This has driven me nuts for days maybe longer...running speeduino 202103 firmware on a custom sheild, trying to add an auxillary input channel to display voltage on A7. Using AUX Input 0.

It would seem that the only way speedy reports the voltages or possibly even measures the voltages is to have A3 enabled and read into any other Aux gauge.

As a work around I have A3 enabled into AUX Input 15, and then using A7 as intended.

Tried many combinations of Analog Ax into AUX Input XX and the only one that seems to help me is A3 into any Aux input.

Am I going nuts? Is this a known bug or something corrupt in my setups?..tried 2 diff ECU same design same problemo.

I assume someone else out there is using this feature but didn't seem much using search in this forum.

 

Give the A3 thing a try please…

 

From: transi01 ***@***.***> 
Sent: May 11, 2021 8:51 AM
To: noisymime/speeduino ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [noisymime/speeduino] Teensy Analog input @ A6 doesn't work (#579)

 

Hey Guy's,

it looks like the analog input A6 doesn't work with teensy3.5.
Have done tests with latest two Firmware versions (202012 and 202103) A6 is not useable for eg 2nd baro sensor...... it alway's display's a fix value but not the same as for another analog input port when not connected........ maybe Bug in Firmware

Thanx,

// Transi

**Comment by transi01** [comment]
there seem to be some problems in port definition in version 202103, with developement Build 202104 everything works as it should and A10 and A11 do work also ;-)

// Thomas
