### ISSUE TITLE
Second Spark Table TPS

### ISSUE THREAD

**Issue by stephenbarnes1981** [noisymime/speeduino#581]
When using the second spark table with the load source for the second table set to TPS, the title on the left of the table still displays "Ignition Load: KPA". The follow spot on the table still follows the MAP input, not the TPS. The hardware does appear to be functioning as per the correct settings, it seems to be just the graphical representation of it is not.
![speeduino_bug](https://user-images.githubusercontent.com/65772976/118375177-ea54ca00-b5b7-11eb-8a0f-e7a613aecd95.png)

**Comment by noisymime** [comment]
This was resolved in 9a7ab944d4d99e7cc79bc132bc7581438da3ea07
