### ISSUE TITLE
Issue with Water Injection, with board pin 5 NO2C

### ISSUE THREAD

**Issue by anpelodo** [noisymime/speeduino#582]
The duty cycle on that specific pin is incorrect.

When I use VVT on that pin, the pwm signal works fine (Sometimes the frequency is unstable)

When I disable VVT and enable WMI. The duty cycle doesn't pass over 15% in the range of 1 a 99. when put 100 the output it's LOW (100%). In tuner Studio the limits are missing in the table WMI control table, since I can put values above 100.

PD. this is my first post. If i made a misstake please let me know.

**Comment by noisymime** [comment]
Closing as this is now resolved with #845
