### ISSUE TITLE
Discussion: Missing tooth is offset ATDC in speeduino but BTDC in megasquirt

### ISSUE THREAD

**Issue by mumme74** [noisymime/speeduino#6]
The setting Trigger Angle is defined as After TDC on cyl 1 in speeduino. 
On most engines i have seen (mostly car engines) the missing tooth is defined as Before TDC on cyl 1.

See Delay teeth drawing in megamanual :
http://www.megamanual.com/ms2/wheel.htm

![](http://www.megamanual.com/ms2/misstoothexample.gif)

And more about the this here:
http://www.extraefi.co.uk/wheel_fitting.htm

![](http://www.extraefi.co.uk/Pix/80_no1.JPG)

Note the setting is BTDC not ATDC

**Comment by noisymime** [comment]
Yes, this was intentional. To me, referencing the trigger based on BTDC always seemed a little backwards and I couldn't see any good reason why Megasquirt did it this way as opposed to ATDC. 

It's trivial to change to BTDC if you think it's preferable, but I'm not sure what the advantage is.

**Comment by mumme74** [comment]
>Yes, this was intentional. To me, referencing the trigger based on BTDC always seemed a little backwards and I couldn't see any good reason why Megasquirt did it this way as opposed to ATDC.

Ok I find it quite the opposite, when a car engines flywheel has sync pulse 60deg before TDC it would seem strange to set the value to 300deg instead of just 60. But like you said, its no big issue.


>It's trivial to change to BTDC if you think it's preferable, but I'm not sure what the advantage is.

Well the advantage would be that it works the same way as other systems.
It will probably be easier to point future users to documentation pages like the ones above

**Comment by noisymime** [comment]
Closing this as this is working per design. Understand that other systems may work differently, but Speeduino will continue to use ATDC
