### ISSUE TITLE
STM32F4x1 pin question/problem

### ISSUE THREAD

**Issue by TadyTheFish** [noisymime/speeduino#606]
Hello
I'm trying to make my own ECU with STM32F411 and I came across a small issue
analog input pinO2 = A8 and pinFuelPump = PA8 basically reference the same pin? Or am I mistaken?
Could the pinFuelPump be changed to PA9 ?

https://github.com/noisymime/speeduino/blob/9022bffb0a6af556461721923605b44a73f2def4/speeduino/init.ino#L2275-L2284

**Comment by VitorBoss** [comment]
A8 doesn't mean `PA8` it means analog channel 8, which is PB0

**Comment by TadyTheFish** [comment]
I'm sorry for the false alarm. I got confused because PA0-PA7 is A0 to A7. But the ADC is 8 channel so yes A8 is not PA8...
Thank you
