### ISSUE TITLE
feature request: PWM IDLE Duty Cycle Multiplier

### ISSUE THREAD

**Issue by choyr** [noisymime/speeduino#638]
In my Honda B20 with a 500Hz IACV, a value of 1% has a change of about 150 rpm which is too coarse. Current setting is only 88-89%, with additional 4% from idle up. If possible to add a multiplier (ex. 100% is no change, and 10% is 10% of the final Duty Cycle) to have a better resolution and control.
Thanks
![image](https://user-images.githubusercontent.com/85299549/129958869-92de2a78-667d-4536-8ded-91b8e81873cc.png)

**Comment by shiznit304** [comment]
did you add a flyback diode across your IAC

**Comment by shiznit304** [comment]
I had the same issue with my NB1 Miata. You just need to solder in a diode across the 12v and ground wires in a certain way. That brought my pwm from the 86-89 range down to 20 - 60 range. It also reduced the audible buzzing noise

**Comment by choyr** [comment]
Alright. Let me test it, because i did not put a flyback diode.
    On Sunday, August 22, 2021, 07:57:21 PM GMT+4, shiznit304 ***@***.***> wrote:  
 
 


I had the same issue with my NB1 Miata. You just need to solder in a diode across the 12v and ground wires in a certain way. That brought my pwm from the 86-89 range down to 20 - 60 range. It also reduced the audible buzzing noise

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
