### ISSUE TITLE
TPS DOT as condition for programmable output not working

### ISSUE THREAD

**Issue by shiznit304** [noisymime/speeduino#642]
![image](https://user-images.githubusercontent.com/62686180/130361942-ef02b426-e034-45bc-ba0e-3e5107a6a79c.png)
TPS DOT as a condition appears to do nothing. I want to use TPS DOT to trigger the opening of my supercharger bypass valve.

**Comment by shiznit304** [comment]
I believe Issue #654 is related to this. Perhaps I need to select the item above TPS dot to get it to work. @morrisman1 @afroboltski

**Comment by shiznit304** [comment]
I was able to get TPSDOT to trigger my programmable output but it's not reliable. Maybe the condition check refresh rate is too slow to catch tpsdot reliably?

**Comment by VitorBoss** [comment]
The update rate is 10x/second for all checks. TPSdot is on the list but it can update faster that 15Hz, I'm using it at 30Hz rate
