### ISSUE TITLE
5 cylinder wasted spark output, no cam sensor

### ISSUE THREAD

**Issue by runesmdk** [noisymime/speeduino#668]
How is 5 cylinder wasted spark handled? I have a board with an added 5th ignition channel, and an engine with an unusual cam pattern. 

Can 5cyl wasted spark be implemented to spark 5 channels in succesion, but just every crank revolution, making it wasted spark?

**Comment by noisymime** [comment]
Not sure exactly when this was added, but this capability has been present for some time 👍
