### ISSUE TITLE
Loading Tune corrupts mega2560 and never works again.

### ISSUE THREAD

**Issue by Turbo351w** [noisymime/speeduino#690]
So I am fairly new to the Speeduino community.  I have been searching for related issues but have not found anything.   So I have duplicated on three different Mega boards.   I loaded the latest release 202108 with speed loader.  I then hooked up to Tuner Studio and created a project.   Used the 202108.ini file and all was good.  I was able to bring up the dashboard, connect and see data.    I then started to make mods to the config for my particular application.   I changed number of injectors, cylinders and size of engine.   burned to mega.   All was still good.    Once I went to the Trigger setup menu.  I left as missing tooth and put in 36 for primary base teeth.  put 1 for missing tooth  and just kind of left everything else default.   Burnt that as well all was good.  Then I went back to the Trigger setup and changed from missing tooth to the 36-2-1 and  set the trigger angle to 10.  Burned that to the mega and now it is dead.   I only get "spe  "  out for a signature.  I have reloaded the firmware multiple times both with Speedy Loader and PlatformIO and Arduino IDE.  nothing Fixes this issue.  Somehow it has corrupted the Mega?   I have loaded other firmware for stuff I have done and it appears to work just fine so I am at a loss right now.  I have been using Arduinos for many years and have never see this happen before.   Like I said I have tried on three different boards they work just fine until I load in my .msq File, then they are dead to TunerStudio.

**Comment by noisymime** [comment]
Closing as no response and I haven't been able to reproduce with this trigger.
