### ISSUE TITLE
Feature Request:Boost By Gear enabled in Open Loop

### ISSUE THREAD

**Issue by jackscr12** [noisymime/speeduino#695]
I tried to do this myself but messed it up so am requesting the help of brighter minds to make Boost by Gear be available with Open Loop Boost control as well .  Closed loop is great and all but not everyone wants to spends hours wasting gas to tune the PID when open loop is already set up and working great but would benefit from the option to reduce boost in lower gears. 
Thank you.

**Comment by jackscr12** [comment]
Ok tried Fixed limit as well and still 0 boost duty, when boost by gear is off it works normal.

**Comment by shiznit304** [comment]
@DylanRooijakkers can you help code boost by gear but for open loop

**Comment by shiznit304** [comment]
@jackscr12 ok i pushed another update to the branch. try testing that

**Comment by jackscr12** [comment]
ok so went out again and partial success , constant limit works great  but multiplied gives 100% duty irrespective of table duty or gear or gear %.

**Comment by DylanRooijakkers** [comment]
> @DylanRooijakkers can you help code boost by gear but for open loop

Hello @shiznit304, I would very much like to expand the functionality of this feature, but I am currently busy studying for exams this week and the week after. I think I will have time from the 17th of November onwards. If there are any questions don't hesitate to ask. Cheers, Dylan

**Comment by jackscr12** [comment]
Went out to experiment again with multiplied , with 2% gear and 16% duty in the duty table I get 16% total duty in the logs. Where as before I used 70% in gear and 50% duty in the table and got 100% duty in the logs. So the multiplication algorithm is wonky somehow

**Comment by shiznit304** [comment]
what if you do 100% gear, at whatever duty cycle, do you still get the duty cycle value?

**Comment by jackscr12** [comment]
100% gear gives 100% duty, it's very weird how it behaves for example 30% gear and 46% duty in table gave me 34% actual duty , but if the table duty is 50% it goes to 100% actual duty in 5th gear , but I set 10% and than 20% in second gear and 36% table and it gave me 100% actual ,

**Comment by shiznit304** [comment]
@DylanRooijakkers wanna give it a shot

**Comment by shiznit304** [comment]
this can be closed @jackscr12
