### ISSUE TITLE
Subaru 6/7 tooth trigger

### ISSUE THREAD

**Issue by noisymime** [noisymime/speeduino#70]
https://speeduino.com/forum/viewtopic.php?f=12&t=80&p=16868&hilit=subaru#p16868

![image](https://cloud.githubusercontent.com/assets/138502/23540231/2218fe04-0034-11e7-9b56-187e8b6a9b35.png)

![image](https://cloud.githubusercontent.com/assets/138502/23540238/2f5572aa-0034-11e7-8052-69def56f2f21.png)

![image](https://cloud.githubusercontent.com/assets/138502/23540251/3c665b8a-0034-11e7-8081-db6b147222c8.png)

![image](https://cloud.githubusercontent.com/assets/138502/23540258/44493a34-0034-11e7-8ece-f96870be73a5.png)

**Comment by noisymime** [comment]
![image](https://cloud.githubusercontent.com/assets/138502/24540548/7b64001e-163f-11e7-8c71-2000d440ce08.png)
Adding version of the timing chart that's actually readable

**Comment by Koop2k** [comment]
![subaru cam sensor](https://user-images.githubusercontent.com/26174331/28841184-a8796312-76f9-11e7-9259-3b52c7e291fd.jpg)
Thought this could be usable here.

**Comment by mstevanin4** [comment]
According to my email to Josh on 19.07.2017, the feature was tested successfully. I think this issue can be closed.

**Comment by noisymime** [comment]
Great, thanks for the reminder!

**Comment by noisymime** [comment]
Composite log for reference: https://i.imgur.com/0aR4gIJ.png
