### ISSUE TITLE
idle.ino

### ISSUE THREAD

**Issue by AmesisProject** [noisymime/speeduino#711]
Hello, I am not sure because I am new to code, but I do not understand why there is a second "case 2" in the file idle.ino line 150.
I think it should be the 4. If it's the 4 I can pullrequest the correction.
Thank you
![SharedScreenshot](https://user-images.githubusercontent.com/57772906/142255192-64c38bdb-f0d9-451f-9ed4-5a868401d7bd.jpg)

**Comment by github-account-0** [comment]
You are right but that is just a comment (noted by the "//") with a wrong or outdated number.  Comments are not compiled into the program and does not affect the program in any way.  They are only there as a reference to help programmers understand what a specific piece of code does.

**Comment by AmesisProject** [comment]
Yes I know it's a comment. But I wanted to be sure I understood. It wasn't a criticism at all. It is that I explore the code and I try to put together the info.

**Comment by noisymime** [comment]
Closing as this is not an issue, just an outdated comment
