### ISSUE TITLE
Feature Request: Radiator fan indicator

### ISSUE THREAD

**Issue by github-account-0** [noisymime/speeduino#716]
I am working on a pi dashboard using tuner studio and noticed there is no indicator available to see when your radiator fan is running.  It would be nice to have that feature.

I am also curious about adding buttons on the tuner studio dash to turn on your radiator fan and condenser fan.

**Comment by npmstart-pray** [comment]
Since it's possible to have speeduino be a pwm controller for electric cooling fans, might I suggest that along with coolant temp displayed, we can see the duty cycle of the cooling fans? It might make config of Pwm controller a tad more accurate and faster.

**Comment by pazi88** [comment]
> Since it's possible to have speeduino be a pwm controller for electric cooling fans, might I suggest that along with coolant temp displayed, we can see the duty cycle of the cooling fans? It might make config of Pwm controller a tad more accurate and faster.

PWM fan control and duty display here: https://github.com/noisymime/speeduino/pull/637

**Comment by github-account-0** [comment]
> > Since it's possible to have speeduino be a pwm controller for electric cooling fans, might I suggest that along with coolant temp displayed, we can see the duty cycle of the cooling fans? It might make config of Pwm controller a tad more accurate and faster.
> 
> PWM fan control and duty display here: #637

I don't have a strong need for a pwm controlled fan. I just want to show if my rad fan is on or off. I might tackle this in a couple months when I have more free time.

**Comment by npmstart-pray** [comment]
I’ve always felt my fan comes on too late and has to run too strongly because of it. Being able to adjust on/off and duty cycle would be awesome for me. Glad someone has requested it before me

**Comment by github-account-0** [comment]
In testing the fan indicator on the dash shows on and off as expected alongside the radiator fan switching on and off.

**Comment by npmstart-pray** [comment]
Nice!  Now an ammeter reading alternator current output reading would be sweet to verify charging system load.

**Comment by mike501** [comment]
We already have a gauge that shows car system voltage. Doesn't that cover
the alternator? If it's not 14.5 (ISH) volts it's not working properly. If
you wanted a light you could do programmable output to turn on a pin at
lower than X volts.

**Comment by npmstart-pray** [comment]
Not voltage, amperage. The current passing through the electrical system. You know the alternator can deliver 125A or whatever at “12vdc”, but that’s max output. If you put an ammeter on the system you can tell how hard it’s working…like when your electric fans are drawing 30A on high

**Comment by github-account-0** [comment]
I merged #719 into my branch https://github.com/github-account-0/speeduino/tree/Radiator_Cooling_Fan_Indicator and I now have a working radiator cooling fan indicator on my tuner studio dash.
