### ISSUE TITLE
SRT4 36+2-2 decoder [$15]

### ISSUE THREAD

**Issue by noisymime** [noisymime/speeduino#72]
https://speeduino.com/forum/viewtopic.php?f=12&t=80&p=16513&hilit=subaru#p16517

![image](https://cloud.githubusercontent.com/assets/138502/23540434/49af44a4-0035-11e7-97c2-7467f7ac206a.png)

**Comment by ace6598** [comment]
This would make a lot of srt 4 swaps easier to do, and it would be nice to ditch my microsquirt.

**Comment by DeionSi** [comment]
@ace6598 Do you have access to a car with these trigger wheels for testing?

**Comment by ace6598** [comment]
> @ace6598 Do you have access to a car with these trigger wheels for testing?

Sold the car couple months back so I don't anymore, sorry.
