### ISSUE TITLE
3D table bilinear interpolation can return values outside the table 

### ISSUE THREAD

**Issue by adbancroft** [noisymime/speeduino#726]
The fixed point math used by the bi-linear interpolation always rounds down. This can result in a value that is outside the table range.

**Comment by adbancroft** [comment]
In the unit test table, this happens at load 17 & RPM 600

**Comment by VitorBoss** [comment]
Could you please test with #524 if the problem is present too? I think I addressed that.

**Comment by adbancroft** [comment]
Was fixed as part of PR#726
