### ISSUE TITLE
Intermittent PWM Idle at 100% duty cycle

### ISSUE THREAD

**Issue by DeionSi** [noisymime/speeduino#730]
The PWM Idle is intermittent at 100% duty cycle. Example output is below.
![analyzer](https://user-images.githubusercontent.com/26184874/143721975-6f347635-6673-4403-8aa7-7a76349d6662.png)

A workaround is to change
SET_COMPARE(IDLE_COMPARE, IDLE_COUNTER + (idle_pwm_max_count - idle_pwm_cur_value) );
to
SET_COMPARE(IDLE_COMPARE, IDLE_COUNTER + (idle_pwm_max_count - idle_pwm_cur_value) + 1 );

The correct fix is probably to do something like PWM fan is doing. At 100% and 0% duty cycle the PWM is disabled and the pin is just set to on or off.

**Comment by shiznit304** [comment]
this can probably be closed, looks like it was fixed

**Comment by noisymime** [comment]
Ahhh I hadn't realised there was an issue open for this. Yes it was resolved in 464933b38f37391246c19bce5679e817dbb1e0ad
