### ISSUE TITLE
Re bin Y Axis only allowing even numbers.

### ISSUE THREAD

**Issue by AshtonRey** [noisymime/speeduino#737]
When I try to adjust my Y axis for load, speeduino automatically changes my inputted values to only even numbers. But for ALPHA-N I’d like to use the odd numbers for a better tuning of my spark, fuel, and AFR maps.  Please see image below of what I am referring too. Thanks!!

![20AA58E5-9212-4FB4-A0E8-813AE784F3C3](https://user-images.githubusercontent.com/95573647/144747673-0ac314a4-f15a-4138-808d-8982bccf1478.jpeg)

**Comment by LPG2CV** [comment]
it's done that way to save memory space
the firmware interpolates the values, so it shouldn't be an issue.  so if you enter say 2,4,6 in the table, with corresponding VE of 28,30,36, then if tps is 3, then VE would be 29. 5 tps would return 33.

**Comment by jonbills** [comment]
I'd like to use odd values too.
when VE at 0% TPS is 30 and VE at 2% TPS is 60, interpolation of a value for 1% TPS is a wild guess

**Comment by VitorBoss** [comment]
#608 adresses that and allow you to use 0.5% steps

**Comment by jonbills** [comment]
> #608 adresses that and allow you to use 0.5% steps

ah, I'd thought that was only for AE, but you're right - looks great, will it be merged soon? or should I install and test the branch?

**Comment by noisymime** [comment]
This has been resolved in #608
