### ISSUE TITLE
Possible divide by 100 optimizations

### ISSUE THREAD

**Issue by DeionSi** [noisymime/speeduino#777]
The following functions have divide by 100 operations which could maybe be replaced by divs100/divu100 from libdivide?

boostByGear
wmiControl
sendcanValues
obd_response
correctionAccel
getTSLogEntry
calculateSecondaryFuel
calculateSecondarySpark
loop (fuel calculations)
PW
oneMSInterval (flex reading)
doUpdates
PID::Compute
PID::SetTunings

**Comment by adbancroft** [comment]
I have PW already in PR #756.

**Comment by noisymime** [comment]
Closed with #756
