### ISSUE TITLE
test_schedules fails on master

### ISSUE THREAD

**Issue by DeionSi** [noisymime/speeduino#780]
This is with Speeduino 0.4.3d.

test\test_schedules\test_schedules.cpp:23:test_accuracy_duration_inj1:FAIL: Values Not Within Delta 20 Expected 1000 Was 1040   [FAILED]
test\test_schedules\test_schedules.cpp:34:test_accuracy_duration_inj2:FAIL: Values Not Within Delta 20 Expected 1000 Was 1036   [FAILED]
test\test_schedules\test_schedules.cpp:45:test_accuracy_duration_inj3:FAIL: Values Not Within Delta 20 Expected 1000 Was 1044   [FAILED]
test\test_schedules\test_schedules.cpp:56:test_accuracy_duration_inj4:FAIL: Values Not Within Delta 20 Expected 1000 Was 1036   [FAILED]
test\test_schedules\test_schedules.cpp:134:test_accuracy_duration_ign3:FAIL: Values Not Within Delta 20 Expected 1000 Was 1044  [FAILED]
test\test_schedules\test_schedules.cpp:151:test_accuracy_duration_ign5:FAIL: Values Not Within Delta 20 Expected 1000 Was 1040  [FAILED]

**Comment by noisymime** [comment]
Tests are currently all passing.

If you're still seeing issues, make sure that a valid tune is loaded on the board and raise a new issue if you're still seeing this.
