### ISSUE TITLE
Use 200MHz RTL8722DM?

### ISSUE THREAD

**Issue by poky** [noisymime/speeduino#819]
Hi, I'm wondering what's the requirement spec for the Speeduino mcu?

I came cross to this Realtek RTL8722DM board, spec as following: 
https://www.amebaiot.com/en/amebad/#rtk_amb21

ARMv8M Real-M300 Cortex-M33 compatible MCU @ 200MHz
ARMv8M Real-M200 Cortex-M23 compatible MCU @ 20MHz
Max. 55 GPIOs
4 Hardware timers
Also Wifi + BT5.0

![Screen Shot 2022-04-02 at 9 22 15 PM](https://user-images.githubusercontent.com/138415/161385279-d369e944-c46d-412e-886f-52df7a185495.jpg)

**Comment by noisymime** [comment]
Really there's 2 things to consider

1. I'd need to have a read through the datasheet (Which annoyingly appears to require a sign-up) to see what the configuration of those timers is (Mainly how many channels each one has). 
2. Support for the architecture within PlatformIO. This isn't strictly needed, but it will be an enormous pain to maintain without it. There appears to already be a request for this, but it hasn't gone far: https://github.com/platformio/platformio-core/issues/769

**Comment by poky** [comment]
Thank you for reply!

As for the datasheet, I hate they put the login requirements on a public open docs.
But have found this from the seeedstudio.
https://files.seeedstudio.com/products/102110419/Basic%20documents/UM0401_RTL872xD_Datasheet_v3.4_watermark.pdf

Timer spec as following:

![Screen Shot 2022-04-03 at 10 59 53 AM](https://user-images.githubusercontent.com/138415/161409387-0c280c9c-8d66-4366-acb7-c393aff747ee.jpg)

Hope these helps!

**Comment by noisymime** [comment]
That should be plenty of timer channels, so no issues from a hardware front. 

The main hurdle now would be getting support for this MCU in PlatformIO. There doesn't seem to have been much action on this on the above linked issue, but if that can be achieved then support in Speeduino should be fairly straighforward

**Comment by noisymime** [comment]
Closing this for now as there is currently no path to implementing this until there is support within PlatformIO.
