### ISSUE TITLE
Feature request: Low battery and alternator indicators

### ISSUE THREAD

**Issue by Corey-Harding** [noisymime/speeduino#822]
For those with dashes running tuner studio a user configurable low battery indicator may be useful when engine is off as well as an alternator low/high warning when engine is running.

**Comment by Fera31** [comment]
you can use a programmable output to do that

**Comment by Corey-Harding** [comment]
> you can use a programmable output to do that

I am referring to lighting up a battery and alternator icon on a tuner studio digital dashboard and not a physical light on a traditional analog dash.

**Comment by brunob45** [comment]
For something simple, you could add an indicator directly in tunerstudio. Something like that would work (in speeduino.ini,  around line 1450):
 
 ​   ​indicator​ = { batteryVoltage<11     }, ​"​Battery low"​,   ​"​battery ok"​,       red, black, white,    black

**Comment by Corey-Harding** [comment]
Something like that is what I was looking for.  Thanks

**Comment by Corey-Harding** [comment]
Going to try:
`indicator = { (batteryVoltage < 11.8) || (batteryVoltage > 15) }, "Battery Warning", "Battery OK", red, black, white, black`
