### ISSUE TITLE
Launch control does not work without flat shift

### ISSUE THREAD

**Issue by Assane14** [noisymime/speeduino#837]
Hello, the problem is that I would like to use the launch control itself, but when I turn it on, it doesn't work, it only starts working with the flat shift function. Secondly, I have the impression that setting the flat shift and launch control soft limit absolute timing is connected in a strange way. My firmware 2022.02 PCB Pazi rev2.2 M52. Is anyone able to confirm if this is a problem only for me or is it a software error? Sorry for my english.

**Comment by shiznit304** [comment]
can you share a screenshot of your settings? Here are mine, i've never had issues with launch control accidentally engaging while up shifting or downshifting
![image](https://user-images.githubusercontent.com/62686180/166171868-af357063-2d18-47ea-9c86-9d31521a3ede.png)
