### ISSUE TITLE
Acceleration Enrichment Taper not working?

### ISSUE THREAD

**Issue by ninjawarrior821** [noisymime/speeduino#843]
I think my taper code is having issues. 
![image](https://user-images.githubusercontent.com/45909524/167734787-2b4a1746-f0ec-40cb-8710-b4d1cbb451eb.png)
![image](https://user-images.githubusercontent.com/45909524/167735511-6173532f-6757-4c01-aa85-575b9db9cfdf.png)

I've been noticing some herky jerkys on the highway and it seems the AE is randomly dumping a lot of fuel. I thought it was just a noisy TPS, but it shouldn't been adding that much with the taper.
I dug into the code a little (novice here) and looked at the taper which should be linear, but in actuality I only notice it turn off and on after the taper max.
![image](https://user-images.githubusercontent.com/45909524/167737638-40b57e6b-08fe-4705-80d3-8e3f9ae714a6.png)
![image](https://user-images.githubusercontent.com/45909524/167737700-6aad69b2-3a9c-4374-a0ba-cee427632552.png)

I was wondering if anyone else had this issue. I'm also wondering if it's a similar issue to this fellow (integer vs float):https://forum.arduino.cc/t/calculating-percentages-yields-0-or-100-never-between/255106

Let me know if this is the complete wrong place to be asking for help, or if it's just a hardware issue.

**Comment by noisymime** [comment]
Are you running on version `202202`? I suspect this is more likely related to the issue mentioned in #773 which has been resolved in master. 

The `percentage()` function in Speediuno does not use floats at all, so that thread mentioned is not relevant.

**Comment by ninjawarrior821** [comment]
Fantastic, that looks like it could be it. I'll try loading the master and report back.

**Comment by ninjawarrior821** [comment]
The car is running much better with the master! (I also CNCed an aluminum vTPS adapter to replace a 3D printed one)


![image](https://user-images.githubusercontent.com/45909524/168160042-01649890-b00f-4e26-af87-82bf2ace70ea.png)
I'll continue to log just to make sure everything is set. 
I assume what shows up in MegaLogViewer is at a slower sampling rate than what the board is running at. There appear to be spots where TPS_Dot = 0, but the AE still triggers...

Thanks so much!
I'm a huge fan of what y'all got going here with Speeduino.

**Comment by felipegaspari** [comment]
Should this issue be closed or is it ongoing?

**Comment by VitorBoss** [comment]
> The car is running much better with the master! (I also CNCed an aluminum vTPS adapter to replace a 3D printed one)
> 
> ![image](https://user-images.githubusercontent.com/45909524/168160042-01649890-b00f-4e26-af87-82bf2ace70ea.png) I'll continue to log just to make sure everything is set. I assume what shows up in MegaLogViewer is at a slower sampling rate than what the board is running at. There appear to be spots where TPS_Dot = 0, but the AE still triggers...
> 
> Thanks so much! I'm a huge fan of what y'all got going here with Speeduino.

The firmware samples TPS AE 30 times per second, the log depends a lot of your current frame limitation.
As the TPS resolution increased 2x the TPSdot is more sensitive to small changes, this is desired for alpha-N and short intake manifolds.

**Comment by sbtoonz** [comment]
> Bad news. While the driving has improved, I've been looking at the logs and I believe the issue still remains. I did a quick test where I held the car ~2700rpm and stomped on the throttle. By my estimate the AE should be around 40% with a taper, but the logs show 100%. ![image](https://user-images.githubusercontent.com/45909524/170060039-84c233c1-308d-418b-8702-2fbd53e3f32c.png) The PW and other fuel logs also confirm a 100% was added...

I just checked some logs from driving around 2 days ago and my AE sits at 100% until the TPS variables are met then it will rise to around 140 and then back to flat 100%

**Comment by sbtoonz** [comment]
![Capture](https://user-images.githubusercontent.com/67915879/170072810-a00592f6-9c40-40e4-b259-7bee2abfed9d.PNG)

**Comment by noisymime** [comment]
Need to see some actual tune and log files here. There's not enough info to determine anything based on those comments alone

**Comment by ninjawarrior821** [comment]
Here's the AE settings:
![image](https://user-images.githubusercontent.com/45909524/170094148-8211d51a-0889-4dbb-bb12-b579f368bc1d.png)

So by my calculations at a TPSdot of >1200, then 103*(3600-2750)/(3600-1400) = 40 (or 140 in the logs).

Here's my tune, look for log titled "Looking for AE Taper V3"
[MiataV3.zip](https://github.com/noisymime/speeduino/files/8764923/MiataV3.zip)
:

**Comment by jackscr12** [comment]
Yep just checked my logs and there it is AE enrich going straight down no slope , and it is definitely  something in the code because it is the same tune as it was in april when I was running the last firm and AE was fine.

**Comment by noisymime** [comment]
> Yep just checked my logs and there it is AE enrich going straight down no slope , and it is definitely something in the code because it is the same tune as it was in april when I was running the last firm and AE was fine.

That is normal, there's no taper to end AE. It just comes on, remains on for the 'Accel Time' duration and then turns off. 

The taper variables change the amount of AE that you get, not tapering it off over time

**Comment by noisymime** [comment]
Have confirmed the issue here, both via logs and a unit test I've just put together. 

It's a different issue from the original one resolved above and causes the RPM based taper not to apply. Result is always 100% rather than the tapered amount. Not sure on the cause yet, but expect a fix incoming shortly.

**Comment by ninjawarrior821** [comment]
> Have confirmed the issue here, both via logs and a unit test I've just put together.
> 
> It's a different issue from the original one resolved above and causes the RPM based taper not to apply. Result is always 100% rather than the tapered amount. Not sure on the cause yet, but expect a fix incoming shortly.

My only thought is that the currentStatus.RPM might not be working. Stuck at 0 or something...

**Comment by noisymime** [comment]
Fix has been pushed up. Please test if possible.

**Comment by ninjawarrior821** [comment]
> Fix has been pushed up. Please test if possible.

Thanks! Will do!

**Comment by sbtoonz** [comment]
> > @noisymime Just ran test on latest master my AE logs look identical to [9673dd8](https://github.com/noisymime/speeduino/commit/9673dd8fe62b423a602f1b0ffd90382cd29cb30f)
> > [2022-05-25_10.06.14AEpaTCH.mlg.zip](https://github.com/noisymime/speeduino/files/8772799/2022-05-25_10.06.14AEpaTCH.mlg.zip)
> > Would like to note in my prior logs the AE spike would happen substantially after TPS increase and in these logs it appears to happen 1:1 with my TPS increase
> > I also wanted to note that my AE still shows 100 but on the graph the line is at 0
> > Is 100 translating into 1.00 ? meaning X * 1.00 = Y?
> 
> I think you have the right idea. "100" on the graph should mean 100% of the VE table fuel, which is a multiplier of 1.00. The graph auto scales. so the bottom of the graph is always 100 because AE never takes fuel away.

OK then based on my TPS DOT logged my AE is working accurately.

I do know after pulling down these master changes I had to retune my VE table in spots

**Comment by ninjawarrior821** [comment]
> Fix has been pushed up. Please test if possible.

It's now working as expected! 
![image](https://user-images.githubusercontent.com/45909524/170520663-f517bd07-3901-4508-ab7b-97d854c52a84.png)
The AE only reached 150 instead of 200, so the taper is working.

Thanks all!
