### ISSUE TITLE
Hiccups during Autotune with NEW_COMMS

### ISSUE THREAD

**Issue by theKraid** [noisymime/speeduino#859]
Both me and a friend have been experiencing some kind of hiccup or ignition cut at set time intervals (guesstimate every ~10 seconds) whenever Autotune is running. Presumably every time TunerStudio burns changes automatically?
It seems to be related to serial communication as the problem can be fixed by turning NEW_COMMS off in project properties.
Affected is both 202202 and current master, in 202108 the problem doesn't exist.
Our setups are both DIY-EFI's CORE4 PnP board in our MX5's.

**Comment by noisymime** [comment]
When you're using auto tune, can you try with the `Update Controller` checkbox cleared as see if this makes a difference?

<img width="514" alt="image" src="https://user-images.githubusercontent.com/138502/171518966-28340937-651e-43ce-ac03-4dd9b60e6ae7.png">

If you're compiling yourself on master, you can also try changing the value of `EEPROM_MAX_WRITE_BLOCK` in `storage.cpp` from 24 to say 12 and see if this makes a difference (I'm assuming you're running on a mega2560?)

If the above change does fix the issue, I'll just need to play with the tuning some more and figure out how aggressive I can go on those writes. The current value was chosen to go as fast as possible when loading a tune, but I hadn't actually tested it with auto-tune where it's writing every x seconds, so it might be a bit too aggressive.

**Comment by noisymime** [comment]
Just pushed up a change that should resolve this one.

**Comment by theKraid** [comment]
I could confirm that this was indeed a burn issue as it only happened with the box ticket. Didn't have enough time to recompile and find the breakpoint but you already implemented a fix 👍 Thanks!
