### ISSUE TITLE
TS_CommandButtonHandler 

### ISSUE THREAD

**Issue by smb29** [noisymime/speeduino#863]
TS_CommandButtonHandler
Can someone modify it, to have knock control from TS?

**Comment by Autohome2** [comment]
What is it exactly you want this button to do?

**Comment by smb29** [comment]
https://github.com/noisymime/speeduino/issues/764#issuecomment-1009306068

**Comment by FazxFi** [comment]
Did you mean the knock setting window or something else

**Comment by smb29** [comment]
I want something similar to the Knock settings window.
I think it would be a good thing for the community

**Comment by pazi88** [comment]
Creating knock setting window to TS is not big task and to be honest, there is already knock settings for Speeduino, but it's hidden. Reason being that there is not really any knock sensing done in Speeduino code. I think it will come with speedyknock in future.

**Comment by smb29** [comment]
well, if it's not a big deal, why don't you do it, instead of announcing it?
I know there are 241 mentions of Knock in the code, I even have some uncommented.
But, still, there is no trace in TS of Knock sensor. Not even on the programmable outputs

**Comment by pazi88** [comment]
I mean for the TS GUI. In actual FW it's huge job. And yes it's mostly not done in the FW.

**Comment by smb29** [comment]
I only ask that the TS GUI be modified

**Comment by pazi88** [comment]
> I only ask that the TS GUI be modified

But you can't do anything with it, so what is the point?

**Comment by smb29** [comment]
have at least the option in TS of Knock

**Comment by pazi88** [comment]
> have at least the option in TS of Knock

Yes, but as is, it doesn't do anything. You first would need to code the features to the FW, to be able to use any of that.

**Comment by smb29** [comment]
> > have at least the option in TS of Knock
> 
> Yes, but as is, it doesn't do anything. You first would need to code the features to the FW, to be able to use any of that.

so, everything is encoded in FW, (as far as Knock is concerned)
It does not even serve to assign an analog input in TS?

Just to clarify

**Comment by smb29** [comment]
Thanks

**Comment by smb29** [comment]
https://user-images.githubusercontent.com/62686180/148832992-983b5952-f7b2-41ec-a2dd-1d442a765278.png

How did this user do it?

**Comment by smb29** [comment]
https://user-images.githubusercontent.com/62686180/148832992-983b5952-f7b2-41ec-a2dd-1d442a765278.png

How did this user do it?

**Comment by pazi88** [comment]
> > > have at least the option in TS of Knock
> > 
> > 
> > Yes, but as is, it doesn't do anything. You first would need to code the features to the FW, to be able to use any of that.
> 
> so, everything is encoded in FW, (as far as Knock is concerned) It does not even serve to assign an analog input in TS?
> 
> Just to clarify

Nothing is really done in FW. Just some reservations for settings etc. you can see that gui TS, by uncommenting it in ini. But don't expect anything to work.

**Comment by smb29** [comment]
Ok, 
just to finish and not bother more.
From where you have access to the graphical user interface, in TS?

Thank you for your patience passi

**Comment by smb29** [comment]
good, very kind

**Comment by mike501** [comment]
Im sure it will be done once the hardware / firmware is ready for general
release.

Please remember, this isn't generally released yet so you are taking on
experimental software which may have defects. Any support you get is
because we're all nice people and not guaranteed, ideally you should be
prepared to support this yourself without anyone's assistance.

**Comment by smb29** [comment]
Ok thanks I get it
