### ISSUE TITLE
platformio.ini

### ISSUE THREAD

**Issue by smb29** [noisymime/speeduino#865]
test_build_project_src = test_build_src

**Comment by noisymime** [comment]
What's your actual issue?

`test_build_project_src` is a deprecated option now and hence has been removed. If you're having issues, upgrade your PlatformIO

**Comment by smb29** [comment]
> What's your actual issue?
> 
> `test_build_project_src` is a deprecated option now and hence has been removed. If you're having issues, upgrade your PlatformIO

sorry, but it's in your code

**Comment by noisymime** [comment]
Again, what's your actual issue???

**Comment by smb29** [comment]
> Una vez más, ¿cuál es tu problema real?

does not matter leave it be. forget

**Comment by noisymime** [comment]
> > What's your actual issue?
> > `test_build_project_src` is a deprecated option now and hence has been removed. If you're having issues, upgrade your PlatformIO
> 
> sorry, but it's in your code

The only place it’s used (That I can see) has been commented out: https://github.com/noisymime/speeduino/blob/1d85100ea708fc13c6d8e2efa3be2ce0b1d02d8c/platformio.ini#L18
