### ISSUE TITLE
Speeduino workflow not compiling

### ISSUE THREAD

**Issue by smb29** [noisymime/speeduino#870]
Why doesn't it compile, why haven't I added DIY EFI v0.4.3?
Greetings

**Comment by noisymime** [comment]
What problems are you having? Current master is compiling fine on all supported platforms at the moment

**Comment by pazi88** [comment]
> What problems are you having? Current master is compiling fine on all supported platforms at the moment

Check PR #871

**Comment by smb29** [comment]
I don't want fork. I would like them to be included in .ini

**Comment by smb29** [comment]
I do not want to disturb. Cheers
