### ISSUE TITLE
202207 After ~45min of driving, EGO correction stops working

### ISSUE THREAD

**Issue by Lucas-AirLift** [noisymime/speeduino#893]
Noticed on my drive home. About 45min in to my drive, EGO correction stuck at 100% and would not change regardless of throttle, map or anything else. I was working perfectly up to that point. A power cycle made it start to work again.

**Comment by Tjeerdie** [comment]
I did a 1h+ drive this weekend. I did not see any issue after 45 minutes of driving. It still works after 1+ hour. 
(PID ego with wideband lambda is what i use, i assume the same sort of setup for you?).

**Comment by Lucas-AirLift** [comment]
Ok some more info. I have not been able to capture this happening with a log. I am running a WBO2.com gauge with a new bosch lsu4.2. I have had this happen now with EGO correction set to both simple and PID. Yesterday it stopped working about 30min in to my drive, only to start working again by itself ~10min of driving later. I can tell when it is working or not as I tuned my cruise a but rich and let the ego correction take over. When this happens, no faults or anything are set in TS that I can see.

**Comment by noisymime** [comment]
Suspect that this may be the same issue that was resolved in #942 

If you're still seeing this occur at all, please raise a new issue for this
