### ISSUE TITLE
Idle control no PWM output. Single wire, open PWM STM32

### ISSUE THREAD

**Issue by NickZ1969** [noisymime/speeduino#907]
Not sure if it effects the other processors.
I SOMETIMES get it to function by changing to Stepper, reboot, change back to PWM single wire idle control.
Change back to 202108 and everything works perfect again.
Im using the same pin mapping for both Firmwares, Same hardware and Same car. I have also used the scope on the output.
Tune is the Same on the same controller.

**Comment by NickZ1969** [comment]
i have found what makes it work, i had nothing else PWM turned on, once i enabled Boost, both the boost and PWM idle control worked, But the idle control wont activate until about 2000rpm and then functions normally. If i disable boost control and reboot Idle control doesn't work again.
but enabling boost control and idle works again.
might be the same for VVT, i didn't experiment with it as i wouldn't have thought idle would have needed it. so there is something wrong with the PWM

**Comment by NickZ1969** [comment]
Tjeerd has fix it in the board_stm32_official.h.
Please replace line 269 in board_stm32_official.h with:
#define IDLE_TIMER_ENABLE()  (TIM1)->SR = ~TIM_FLAG_CC4; (TIM1)->DIER |= TIM_DIER_CC4IE; (TIM1)->CR1 |= TIM_CR1_CEN;

**Comment by Tjeerdie** [comment]
PR #908 Is the fix for this
