### ISSUE TITLE
Speedyloader not updating signature in Speeduino

### ISSUE THREAD

**Issue by mppickett** [noisymime/speeduino#911]
I came across a small problem where it looks like Speedyloader doesn't update (always?) the signature in the arduino. In my case, I upgraded to the 202207 firmware using Speedloader and have been using it with Tunerstudio for several weeks with no problem. I got a new phone and reinstalled MSDroid. MSDroid wouldn't connect and complained that the firmware versions didn't match. It said the firmware signature in the Speeduino was "speeduino 202204-dev. I reconnected using Tunerstudio and got a similar error. I repeated the connection to Tunerstudio after shutting down everything and was successful at connecting with no errors.

I serial connected directly to the arduino and executed the "S" command and it responded with "Speeduino 202204-dev." Somehow that signature had persisted after the last Speedyload.

I downloaded the 202207 files, compiled and uploaded them to the Speeduino using the Arduino IDE. That corrected the signature reported by arduino and the MSDroid connected after that point.

Probably an obscure problem, but doing an IDE compile and upload is a workaround. 
![Speeduino signature mismatch](https://user-images.githubusercontent.com/7286315/184032405-2d013a02-6cd4-4431-8d28-674fe0f3ba75.JPG)

**Comment by NickZ1969** [comment]
This comes up if you haven't used the correct INI or haven't adjusted the settings in project properties. Its using the legacy serial comms settings that still have the old signature.
If the correct ini or the settings fixed (Controller type and New comms enabled) in the project settings this will work correctly. these are not carried over from the old tune and have been recently added.

**Comment by mppickett** [comment]
Thanks, Nick. I don't think that's the case, in this example.

 SpeedyLoader (V1.5.1 Windows) always sets the signature in the firmware on the board to "2022.04-dev" and TunerStudio New Coms ignores it if the INI file matches the Project setting. However, the old signature persists on the firmware unless you do a direct IDE load of the firmware.  Not a problem with TunerStudio, but when you use MSDroid on your smartphone to do data logging, it can confuse TunerStudio and sometimes MSDroid and cause an error.

I took my backup V0.4 board and did a series of signature reads and firmware uploads and was able to reliably replicate the problem. I'll upload the screenshots, but the upshot is that the current release of SpeedyLoader always sets the signature to "2022.04-dev." IDE uploads always correctly set the firmware signature. Not a big problem, but maybe it can be touched in the next release of SpeedyLoader.

Signature Before 1st SpeedyLoader
![1_SigBeforeSpdyLoad](https://user-images.githubusercontent.com/7286315/184981017-a9fe0d2e-63eb-4b3e-a2ad-9596c212c037.JPG)

Speedyloader Screen
![2_SpdyLoad](https://user-images.githubusercontent.com/7286315/184981207-f32a3fea-decd-4f5f-a089-e83f06ec3e98.JPG)

Signature After 1st SpeedyLoader
![3_SigAfterSpdyLoad](https://user-images.githubusercontent.com/7286315/184981346-4dbfdfe7-fc08-4ac1-bd57-1914c68b9df7.JPG)

TunerStudio Board Version Setting
![4_BoardSetting](https://user-images.githubusercontent.com/7286315/184981516-194e943f-80b8-4c0e-a6e5-298b6026abe5.JPG)

TunerStudio New Coms Setting
![5_ProjectNewComs](https://user-images.githubusercontent.com/7286315/184981618-442cad4d-dc3d-4fe9-81a9-e1a4b4f4135e.JPG)

TunerStudio Loading a 202207.ini Tune
![6_TSBurnt202207_Tune](https://user-images.githubusercontent.com/7286315/184981881-fb245fb5-39fa-4b88-857a-21b16a9b6e38.JPG)

TunerStudio Project Signature After Burning Tune
![7_TS_AfterBurn](https://user-images.githubusercontent.com/7286315/184982157-242fb4e7-f423-4806-873e-844e0b326acb.JPG)

Firmware Signature After TunerStudio Burning Tune
![8_SigAfterTSBurn](https://user-images.githubusercontent.com/7286315/184982338-774177fd-8c3e-433f-a4c6-71cd59ada73e.JPG)

Firmware Compile and Upload Using IDE
![9_IDE_Upload](https://user-images.githubusercontent.com/7286315/184982547-251c2fea-11f9-4dc2-8deb-10f6aed66922.JPG)

Firmware Signature After IDE Upload
![10_SigAfterIDEUpload](https://user-images.githubusercontent.com/7286315/184982855-7b73e3ff-8e92-49d6-9b0d-c7a4fae4a5d0.JPG)

Signature After 2nd SpeedyLoader Upload
![11_SigAfter2ndSpdyLoad](https://user-images.githubusercontent.com/7286315/184983002-d4ff0aff-8096-488f-b3a9-cbc5107b8224.JPG)

Signature After 2nd IDE Upload
![12_SigAfter2ndIDEUpload](https://user-images.githubusercontent.com/7286315/184983175-4f1b762a-9d36-4f68-8e58-627f8524c7bc.JPG)

**Comment by NickZ1969** [comment]
Strange you are getting this, Im using speedyloader and uploading about 5 ECU's a day but not having your issue.
Speedyloader doesn't change the code, it just downloads a precompiled bin file.
![Screen Shot 2022-08-17 at 7 40 21 am](https://user-images.githubusercontent.com/20110420/184990241-259484e5-c49f-41be-a2a6-e3c393f292dc.png)
![Screen Shot 2022-08-17 at 7 39 52 am](https://user-images.githubusercontent.com/20110420/184990251-cf48eedf-7762-4747-ad73-3e1cf45855ed.png)
If we look at the code in Legacy you will see the signature it's displaying when you are requesting it in you examples.

**Comment by NickZ1969** [comment]
I think i know your issue. did you use speedyloader when the new firmware was released, The very first one had the wrong signature and was updated shortly after with the new signature, so if you use speedyloader it will keep burning the BIN file you originally had and doesn't download a new one each time. you need to locate the Speedyloader directory and delete the 202207 bin file you have and then restart speedyloader and it should download the correct bin with the fixed signatures, you IDE burned version would be the fixed version and working correctly.

**Comment by mppickett** [comment]
Bingo. On Windows SpeedyLoader puts the binary file in the <username>/download directory with a .hex extension. As you noted, it doesn't redownload it everytime. You can force it to download by deleting the file. In my case, I deleted the 202207.hex file and when I reran Speedyloader it redownloaded 202207.hex with the correct signature. Problem solved.

Many thanks for the sleuthing!

**Comment by noisymime** [comment]
Closing as this was a temporary issue. 

If anyone else runs across this, delete the *.hex files from your Downloads directory
