### ISSUE TITLE
Fuel Injector Timing has wrong description

### ISSUE THREAD

**Issue by HWright9** [noisymime/speeduino#955]
Fuel injector close angles are actually start angles as implemented in the firmware.

I think it would be better if they really were close angles since this would give better timing to intake valve opening with variable pulse widths, but this is not how it's implemented now. To fix this the fuel scheduler should swap the start and the end times, similar to how ignition angles are done. Alternately if start angles are desired, change the .ini to reflect this.

![image](https://user-images.githubusercontent.com/87687708/198511878-12714b55-9208-4997-a33b-1a6565ea512e.png)

Traceback through the sofware:

![image](https://user-images.githubusercontent.com/87687708/198512112-e4276887-6288-4290-8f2d-802e698e35f0.png)
calculated from:
![image](https://user-images.githubusercontent.com/87687708/198512191-d305394f-744b-4e9d-8da7-5da01726ccc6.png)
calculated from:
![image](https://user-images.githubusercontent.com/87687708/198512295-1e03a794-8dd2-444e-9e21-82f0f0b2709c.png)
calculated from:
![image](https://user-images.githubusercontent.com/87687708/198512365-540dc21f-808d-462d-a06d-02ef4e633717.png)

**Comment by noisymime** [comment]
Have you verified this on a scope? I believe the current implementation is correct. 

You have this line:
`unsigned int PWdivTimerPerDegree = div(currentStatus.PW1, timePerDegree).quot; //How many crank degrees the calculated PW will take at the current speed`

And then within the `calculateInjectorStartAngle()` function you have:
`tempInjectorStartAngle -= PWdivTimerPerDegree;`

That line is taking the lookup from the injector angle 2d table and subtracting the number of degrees that the PW goes for. The result is the start angle.

**Comment by HWright9** [comment]
Ok I missed that. tricky.
