### ISSUE TITLE
TunerStudio sends wrong ADC scaling for sensor calibration values

### ISSUE THREAD

**Issue by DeionSi** [noisymime/speeduino#957]
I think I found a problem with TunerStudio. The ADC scaling of the sensor calibration tables in Speeduino goes from 0 to 992 instead of 0 to 1023. Looking TunerStudios std_ms2gentherm.log the Volts scaling goes from 0 to 4.844 instead of 0 to 5.

[std_ms2gentherm.log](https://github.com/noisymime/speeduino/files/9891796/std_ms2gentherm.log)

Coolant output of "z" command to speeduino (prints calibration values).
0, 216
32, 216
64, 185
96, 166
128, 153
160, 143
192, 136
224, 129
256, 123
288, 118
320, 113
352, 109
384, 105
416, 101
448, 97
480, 93
512, 90
544, 87
576, 83
608, 80
640, 76
672, 73
704, 70
736, 66
768, 62
800, 57
832, 52
864, 47
896, 41
928, 33
960, 21
992, 0

At lower temperatures this causes a noticeable temperature difference. In my case:
17C -> 12C
1C -> -7C
-7C -> -19C
-20C -> -40C

Do we have any direct contacts at TunerStudio this can be reported to?

**Comment by DeionSi** [comment]
Actually, it seems the issue is in Speeduino. I'm halfway done with the fix.

**Comment by pazi88** [comment]
Whst speeduino version you are working on. Master uses 32 values. Not 1024.

**Comment by DeionSi** [comment]
Yes, it uses only 32 values. But those values are scaled from 0 to 992 but should be scaled from 0 to 1023.
