### ISSUE TITLE
Staged Injection table mode only considers the first row of the table

### ISSUE THREAD

**Issue by theKraid** [noisymime/speeduino#998]
A friend and I are bench testing a staged injection setup for our naturally aspirated rotaries.
We discovered that in table mode for some reason only the first row of the table is considered for the calculation despite the cursor in TunerStudio moving across the table in height also.

Below is a recording that show the behavior. Pay attention to the injector LEDs as the cursor is moving across the table
Keep in mind this is a TPS-load based (Alpha-N) setup, maybe in MAP-based its fine but we have not tested it this way.
Here's the tune: https://tunes.speeduino.com/#/t/p47vKl3LfI/tune

https://user-images.githubusercontent.com/37898397/216430393-671c8ace-bd09-4208-952d-5ab3670cea40.mp4

**Comment by noisymime** [comment]
Have confirmed this, looks like the case for table based staging with TPS as load source was never handled.

I’ll get this added shortly.

**Comment by noisymime** [comment]
Fixed now in master and fixes branches.

**Comment by theKraid** [comment]
Awesome! Thank you so much
